networks:
  external:
    external: true
    name: public

volumes:
  members-db:

services:
  app:
    image: wolbodo/members:latest
    restart: always
    depends_on:
      - db
    networks: [external, default]
    command: node .
    expose:
      - 80
    env_file: .env
    environment:
      PORT: 80
      VIRTUAL_HOST: members.wolbodo.nl, member.wolbodo.nl, people.wolbodo.nl, mensen.wolbodo.nl, menschen.wolbodo.nl, leden.wolbodo.nl
      CERT_NAME: wildcard

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    command: postgres
    environment:
      POSTGRES_INITDB_ARGS: --data-checksums
    env_file: .env
    volumes:
      - members-db:/var/lib/postgresql/data
