version: "3.8"

networks:
  default:
    external:
      name: wolbodo

volumes:
  node_modules:
  __sapper__:
  yarn-cache:

services:
  app:
    restart: always
    image: node:alpine
    depends_on:
      - graphql
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
      - "yarn-cache:/usr/local/share/.cache/yarn/"
    command: sh -c "cd app; yarn install --frozen-lockfile; yarn run dev -p 80"
    ports:
      - "5000:80"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_INITDB_ARGS: --data-checksums
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./db/data:/var/lib/postgresql/data

  graphql:
    restart: always
    build:
      context: ./graphql
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "5001:80"
