
Query unique roles

{
  auth_person_role(distinct_on:role) {
    role
  }
}

{
  auth_person(where:{id:{_eq:1}}) {
    name
    roles(where:{
      valid_from:{_lt:"NOW"},
      _or:[
        {valid_till:{_gt:"NOW"}},
        {valid_till:{_is_null:true}},
      ]
    }) {
      role
      valid_from
      valid_till
    }
  }
}