query PersonById($id: Int, $isBoard: Boolean = false, $isSelf: Boolean = false)
@cache(policy: NetworkOnly) {
	auth_person(where: { id: { _eq: $id } }, limit: 1) {
		name
		firstname
		lastname
		email
		phone
		address
		zipcode
		city
		country
		note
		id
		created
		modified

		...PersonRoles

		bankaccount @include(if: $isBoard)
		bankaccount @include(if: $isSelf)
		key_code @include(if: $isBoard)
	}
}
