query PersonByName($name: String, $isBoard: Boolean = false, $isSelf: Boolean = false)
@cache(policy: NetworkOnly) {
	auth_person(where: { name: { _ilike: $name } }, limit: 1) {
		name
		firstname
		lastname
		email
		phone
		address
		zipcode
		city
		country
		note
		id
		created
		modified

		allow_door
		allow_register

		...PersonRoles

		bankaccount @include(if: $isBoard)
		bankaccount @include(if: $isSelf)
		key_code @include(if: $isBoard)
	}
}
