CREATE EXTENSION pgcrypto;
CREATE EXTENSION btree_gist;

CREATE SCHEMA public;
DROP TABLE IF EXISTS public.user CASCADE;
DROP TABLE IF EXISTS public.role CASCADE;
DROP TABLE IF EXISTS public.user_role CASCADE;
